version: "3.8"
services:
  app:
    container_name: sight_app
    build:
      context: ./
      dockerfile: Dockerfile
      target: publisher-dev
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - app-network
  db:
    container_name: sight_db
    image: postgres:14.5
    environment:
      POSTGRES_DB: "sightdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pgpwd"
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge