--
-- PostgreSQL database dump
--

-- Dumped from database version 14.3
-- Dumped by pg_dump version 14.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: sight; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sight (
    id integer NOT NULL,
    latitude double precision,
    longitude double precision
);


ALTER TABLE public.sight OWNER TO postgres;

--
-- Name: sight_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sight ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sight_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: sight; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sight (id, latitude, longitude) FROM stdin;
1	55.75	37.62
2	53.72	91.43
3	43.43	39.92
4	47.11	39.42
5	56.4	38.71
6	54.51	37.07
7	54.9	52.32
8	64.73	177.51
9	44.89	37.32
10	52.54	103.89
11	56.08	86.03
12	67.56	33.4
13	55.39	43.84
14	44.99	41.12
15	44.15	133.28
16	64.54	40.54
17	57.01	61.46
18	46.35	48.04
\.


--
-- Name: sight_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sight_id_seq', 18, true);


--
-- Name: sight sight_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sight
    ADD CONSTRAINT sight_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

